#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistas.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AplicacionWeb")]
	public partial class AplicacionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttbl_tipo_persona(tbl_tipo_persona instance);
    partial void Updatetbl_tipo_persona(tbl_tipo_persona instance);
    partial void Deletetbl_tipo_persona(tbl_tipo_persona instance);
    partial void Inserttbl_persona(tbl_persona instance);
    partial void Updatetbl_persona(tbl_persona instance);
    partial void Deletetbl_persona(tbl_persona instance);
    #endregion
		
		public AplicacionDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Aplicacion"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AplicacionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AplicacionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AplicacionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AplicacionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_tipo_persona> tbl_tipo_persona
		{
			get
			{
				return this.GetTable<tbl_tipo_persona>();
			}
		}
		
		public System.Data.Linq.Table<tbl_persona> tbl_persona
		{
			get
			{
				return this.GetTable<tbl_persona>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CrearMensajero")]
		public int sp_CrearMensajero([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombrePersona, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string apellidoPersona, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string contrasenaPersona, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string salt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> edad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombrePersona, apellidoPersona, usuario, contrasenaPersona, salt, edad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CrearCliente")]
		public int sp_CrearCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombrePersona, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string apellidoPersona, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string contrasenaPersona, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string salt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> edad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombrePersona, apellidoPersona, usuario, contrasenaPersona, salt, edad);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_tipo_persona")]
	public partial class tbl_tipo_persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTipoPersona;
		
		private string _nombreTipoPersona;
		
		private byte _estado;
		
		private EntitySet<tbl_persona> _tbl_persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipoPersonaChanging(int value);
    partial void OnidTipoPersonaChanged();
    partial void OnnombreTipoPersonaChanging(string value);
    partial void OnnombreTipoPersonaChanged();
    partial void OnestadoChanging(byte value);
    partial void OnestadoChanged();
    #endregion
		
		public tbl_tipo_persona()
		{
			this._tbl_persona = new EntitySet<tbl_persona>(new Action<tbl_persona>(this.attach_tbl_persona), new Action<tbl_persona>(this.detach_tbl_persona));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoPersona", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTipoPersona
		{
			get
			{
				return this._idTipoPersona;
			}
			set
			{
				if ((this._idTipoPersona != value))
				{
					this.OnidTipoPersonaChanging(value);
					this.SendPropertyChanging();
					this._idTipoPersona = value;
					this.SendPropertyChanged("idTipoPersona");
					this.OnidTipoPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreTipoPersona", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombreTipoPersona
		{
			get
			{
				return this._nombreTipoPersona;
			}
			set
			{
				if ((this._nombreTipoPersona != value))
				{
					this.OnnombreTipoPersonaChanging(value);
					this.SendPropertyChanging();
					this._nombreTipoPersona = value;
					this.SendPropertyChanged("nombreTipoPersona");
					this.OnnombreTipoPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="TinyInt NOT NULL")]
		public byte estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipo_persona_tbl_persona", Storage="_tbl_persona", ThisKey="idTipoPersona", OtherKey="idTipoPersona")]
		public EntitySet<tbl_persona> tbl_persona
		{
			get
			{
				return this._tbl_persona;
			}
			set
			{
				this._tbl_persona.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_persona(tbl_persona entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipo_persona = this;
		}
		
		private void detach_tbl_persona(tbl_persona entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipo_persona = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_persona")]
	public partial class tbl_persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPersona;
		
		private string _nombrePersona;
		
		private string _apellidoPersona;
		
		private string _usuarioPersona;
		
		private string _contrasenaPersona;
		
		private string _salt;
		
		private byte _edad;
		
		private byte _estado;
		
		private int _idTipoPersona;
		
		private string _emailPersona;
		
		private EntityRef<tbl_tipo_persona> _tbl_tipo_persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPersonaChanging(int value);
    partial void OnidPersonaChanged();
    partial void OnnombrePersonaChanging(string value);
    partial void OnnombrePersonaChanged();
    partial void OnapellidoPersonaChanging(string value);
    partial void OnapellidoPersonaChanged();
    partial void OnusuarioPersonaChanging(string value);
    partial void OnusuarioPersonaChanged();
    partial void OncontrasenaPersonaChanging(string value);
    partial void OncontrasenaPersonaChanged();
    partial void OnsaltChanging(string value);
    partial void OnsaltChanged();
    partial void OnedadChanging(byte value);
    partial void OnedadChanged();
    partial void OnestadoChanging(byte value);
    partial void OnestadoChanged();
    partial void OnidTipoPersonaChanging(int value);
    partial void OnidTipoPersonaChanged();
    partial void OnemailPersonaChanging(string value);
    partial void OnemailPersonaChanged();
    #endregion
		
		public tbl_persona()
		{
			this._tbl_tipo_persona = default(EntityRef<tbl_tipo_persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPersona", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPersona
		{
			get
			{
				return this._idPersona;
			}
			set
			{
				if ((this._idPersona != value))
				{
					this.OnidPersonaChanging(value);
					this.SendPropertyChanging();
					this._idPersona = value;
					this.SendPropertyChanged("idPersona");
					this.OnidPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrePersona", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombrePersona
		{
			get
			{
				return this._nombrePersona;
			}
			set
			{
				if ((this._nombrePersona != value))
				{
					this.OnnombrePersonaChanging(value);
					this.SendPropertyChanging();
					this._nombrePersona = value;
					this.SendPropertyChanged("nombrePersona");
					this.OnnombrePersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoPersona", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellidoPersona
		{
			get
			{
				return this._apellidoPersona;
			}
			set
			{
				if ((this._apellidoPersona != value))
				{
					this.OnapellidoPersonaChanging(value);
					this.SendPropertyChanging();
					this._apellidoPersona = value;
					this.SendPropertyChanged("apellidoPersona");
					this.OnapellidoPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioPersona", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usuarioPersona
		{
			get
			{
				return this._usuarioPersona;
			}
			set
			{
				if ((this._usuarioPersona != value))
				{
					this.OnusuarioPersonaChanging(value);
					this.SendPropertyChanging();
					this._usuarioPersona = value;
					this.SendPropertyChanged("usuarioPersona");
					this.OnusuarioPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasenaPersona", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string contrasenaPersona
		{
			get
			{
				return this._contrasenaPersona;
			}
			set
			{
				if ((this._contrasenaPersona != value))
				{
					this.OncontrasenaPersonaChanging(value);
					this.SendPropertyChanging();
					this._contrasenaPersona = value;
					this.SendPropertyChanged("contrasenaPersona");
					this.OncontrasenaPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salt", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string salt
		{
			get
			{
				return this._salt;
			}
			set
			{
				if ((this._salt != value))
				{
					this.OnsaltChanging(value);
					this.SendPropertyChanging();
					this._salt = value;
					this.SendPropertyChanged("salt");
					this.OnsaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad", DbType="TinyInt NOT NULL")]
		public byte edad
		{
			get
			{
				return this._edad;
			}
			set
			{
				if ((this._edad != value))
				{
					this.OnedadChanging(value);
					this.SendPropertyChanging();
					this._edad = value;
					this.SendPropertyChanged("edad");
					this.OnedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="TinyInt NOT NULL")]
		public byte estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoPersona", DbType="Int NOT NULL")]
		public int idTipoPersona
		{
			get
			{
				return this._idTipoPersona;
			}
			set
			{
				if ((this._idTipoPersona != value))
				{
					if (this._tbl_tipo_persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipoPersonaChanging(value);
					this.SendPropertyChanging();
					this._idTipoPersona = value;
					this.SendPropertyChanged("idTipoPersona");
					this.OnidTipoPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailPersona", DbType="VarChar(50)")]
		public string emailPersona
		{
			get
			{
				return this._emailPersona;
			}
			set
			{
				if ((this._emailPersona != value))
				{
					this.OnemailPersonaChanging(value);
					this.SendPropertyChanging();
					this._emailPersona = value;
					this.SendPropertyChanged("emailPersona");
					this.OnemailPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipo_persona_tbl_persona", Storage="_tbl_tipo_persona", ThisKey="idTipoPersona", OtherKey="idTipoPersona", IsForeignKey=true)]
		public tbl_tipo_persona tbl_tipo_persona
		{
			get
			{
				return this._tbl_tipo_persona.Entity;
			}
			set
			{
				tbl_tipo_persona previousValue = this._tbl_tipo_persona.Entity;
				if (((previousValue != value) 
							|| (this._tbl_tipo_persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_tipo_persona.Entity = null;
						previousValue.tbl_persona.Remove(this);
					}
					this._tbl_tipo_persona.Entity = value;
					if ((value != null))
					{
						value.tbl_persona.Add(this);
						this._idTipoPersona = value.idTipoPersona;
					}
					else
					{
						this._idTipoPersona = default(int);
					}
					this.SendPropertyChanged("tbl_tipo_persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
